name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-full python3-venv git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libjpeg-dev libpng-dev zipalign adb aidl libstdc++6  # Includes AIDL, zipalign, adb from fix

    - name: Set up Java
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: |
        python3 -m venv buildozer_env
        echo "$GITHUB_WORKSPACE/buildozer_env/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        pip install --upgrade buildozer Cython==0.29.33

    - name: Set up Android SDK (trigger download)
      run: |
        yes | buildozer android debug  # Triggers SDK install; ignore initial error

    - name: Install specific build-tools 29.0.0 via sdkmanager
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;29.0.0"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update

    - name: Clean build-tools directory (keep only 29.0.0)
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        cd $ANDROID_SDK_ROOT/build-tools
        ls | grep -v "29.0.0" | xargs rm -rf  # Delete other versions

    - name: Set permissions on SDK
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        sudo chmod -R 777 $ANDROID_SDK_ROOT

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug  # Auto-accept licenses, verbose

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
