name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04  # Stable Ubuntu for 2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libjpeg-dev libpng-dev aidl  # aidl via apt
        pip3 install --upgrade Cython==0.29.33 buildozer

    - name: Set up Android SDK
      run: |
        # Download and set up Android SDK command-line tools
        mkdir -p android-sdk/cmdline-tools
        cd android-sdk/cmdline-tools
        wget -O latest.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip  # Latest as of 2025
        unzip latest.zip
        mv cmdline-tools latest
        export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

    - name: Accept SDK licenses and install build-tools
      run: |
        export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk
        yes | sdkmanager --licenses  # Accept all licenses
        sdkmanager "build-tools;29.0.0" "platforms;android-33" "platform-tools"  # Install build-tools 29.0.0 for AIDL
        sdkmanager --update  # Update SDK

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
