name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .  # Build in root dir (where main.py and spec are)
        buildozer_version: stable  # Or 'master' for latest

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ${{ steps.buildozer.outputs.filename }}
